Suppress browse nearby for items with no callnumber
sul-dlss/SearchWorks pull request #3421
Opened 2023-08-15 20:55 UTC by marlo-longley

Fixes #3405

2023-08-15 21:16 UTC, cbeer commented
I guess I'm unclear why `Item#browsable?` is true for these records. It feels like we did something wrong... somewhere... along the way.

2023-08-15 21:33 UTC, thatbudakguy approved these changes

2023-08-15 21:38 UTC, thatbudakguy commented
Hmm. Yeah, it seems...not great to have a nonexistent call number be typed as "LC"

2023-08-15 21:53 UTC, cbeer requested changes
That's (presumably?) just the data though. I don't think we want to go second-guessing it too much. The mystery remains, why do we have all the pieces that `#browseable?` thinks we need, but we end up with nothing to browse?

It seems to me that either `#browseable?` is missing a condition, or we've failed to inject the right data in our FOLIO mappings. I think we should look into the underlying issue instead of patching over it in `#callnumber_type`.

2023-08-17 01:12 UTC, cbeer approved these changes

2023-08-17 01:12 UTC, merged