Only show the MHLD latest information once
sul-dlss/SearchWorks pull request #3946
Opened 2024-02-14 19:49 UTC by cbeer

![Screenshot 2024-02-14 at 11 48 54](https://github.com/sul-dlss/SearchWorks/assets/111218/c800e181-73fe-4547-821e-e2bd647b3b54)

2024-02-15 23:44 UTC, dnoneill commented
Another good record to test is: https://searchworks.stanford.edu/view/520112

2024-02-16 16:17 UTC, jcoyne requested changes

2024-02-16 16:17 UTC, jcoyne commented on app/components/access_panels/library_location_component.html.erb
> +  <% if location.mhld.present? && location.mhld.first.latest_received %>
Isn't this first clause already established on line 7?
```suggestion
  <% if location.mhld.first.latest_received %>
```

2024-02-16 21:52 UTC, jcoyne approved these changes

2024-02-16 21:52 UTC, merged